[package]
name = "moly-widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }
makepad-code-editor = { git = "https://github.com/makepad/makepad", branch = "rik" }
futures-core = "0.3.31"