[package]
name = "moly-mini"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
futures-core = "0.3.31"
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }
moly-widgets = { path = "../moly-widgets" }
