[package]
name = "moly-mini"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.6"
futures = "0.3.31"
futures-core = "0.3.31"
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }
moly-widgets = { path = "../moly-widgets" }
reqwest = { version = "0.12.12", features = ["json", "stream"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
